### ISSUE TITLE
Add proper mentions to awesome-uniswap-hooks

### ISSUE THREAD

**Issue by fewwwww** [0xaaiden/uniswaphooks#3]
I notice that [your content](https://github.com/search?q=repo%3A0xaaiden%2Funiswaphooks+language%3AMDX&type=code) is based almost entirely on, or largely inspired by [awesome-uniswap-hooks](https://github.com/fewwwww/awesome-uniswap-hooks). Sadly to me that nowhere in your repo, is there an acknowledgement or mention of awesome-uniswap-hooks.

As a member of the open source community and a contributor to awesome-uniswap-hooks, I am very disappointed. It's frustrating to have your work taken without any mention or acknowledgement.

I'd like to see you add the source of the information pointing to awesome-uniswap-hooks and its repo link in a prominent place in the project, or the readme file.

Thank you for your contribution to open source and public goods.

**Comment by 0xaaiden** [comment]
Thank you for pointing this out. I value the efforts of open-source contributions and the oversight was certainly not intentional.

The project is pre-launch and I'm already working on an acknowledgements page located at /src/data/pages/acknowledgements.mdx. I'll prominently link to it soon . I'd like to clarify that the content in our repo draws from you work in awesome-uniswap-hooks (and I'm truly grateful for your efforts there) but also from the Uniswap Foundation's internal database of submitted hooks.

I'd love to find ways to collaborate and mutually benefit both projects. Your feedback is appreciated.

**Comment by fewwwww** [comment]
Thanks a lot for the clarification🙏
